services:
  - type: web
    name: vyparai-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ML_SERVICE_URL
        sync: false
