import { Bell, Search } from 'lucide-react';
import { BottomNav, Button, Card, TopBrand } from '../components/ui';
import { useData } from '../context/DataContext';
import { expiringInDays } from '../utils/analytics';
import { Link } from 'react-router-dom';
import { useState } from 'react';

export default function(){const {products}=useData();const [tab,setTab]=useState('All Items');const filtered=tab==='Low Stock'?products.filter(p=>p.stock<20):tab==='Expiring Soon'?expiringInDays(products,7):products;
return <main className='max-w-md mx-auto min-h-screen bg-brand-light p-4 pb-24'><header><div className='flex justify-between items-center'><div><TopBrand/><p className='text-xs text-slate-500'>Inventory Dashboard</p></div><div className='flex gap-2'><Search size={18}/><Bell size={18}/></div></div></header><div className='flex gap-4 mt-4 text-sm'>{['All Items','Low Stock','Expiring Soon'].map(t=><button key={t} onClick={()=>setTab(t)} className={`pb-1 ${tab===t?'text-brand-primary border-b-2 border-brand-primary':'text-slate-500'}`}>{t}</button>)}</div><div className='flex justify-between mt-4'><h3 className='text-xs tracking-wider'>CURRENT STOCK</h3><Link to='/add-product'><Button className='py-2 text-sm'>+ Add Product</Button></Link></div><div className='space-y-3 mt-3'>{filtered.map(p=>{const expDays=(new Date(p.expiry_date).getTime()-Date.now())/86400000;return <Card key={p.id} className='p-3 flex gap-3'><div className='h-16 w-16 bg-slate-100 rounded-xl'/><div className='flex-1'><p className='font-semibold'>{p.name}</p><p className='text-xs text-slate-500'>CATEGORY: {p.category.toUpperCase()}</p>{p.stock<20 && <span className='text-xs bg-red-100 text-red-500 px-2 py-1 rounded-full'>LOW STOCK</span>} {expDays<=7 && <span className='text-xs bg-orange-100 text-orange-500 px-2 py-1 rounded-full ml-1'>EXPIRING SOON</span>}<p className='text-sm mt-1'>IN STOCK: {p.stock} Units</p><p className='text-xs text-slate-500'>Expiry: {new Date(p.expiry_date).toLocaleDateString()}</p></div></Card>})}</div><Link to='/add-product' className='fixed bottom-20 left-1/2 -translate-x-1/2 h-14 w-14 rounded-full bg-brand-primary text-white grid place-items-center text-2xl'>+</Link><BottomNav/></main>}
