import { Bell, Bot, ChevronLeft, Mic, ScanLine } from 'lucide-react';
import { Link, Route, Routes } from 'react-router-dom';
import { Line } from 'react-chartjs-2';
import { Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, Tooltip } from 'chart.js';
import { BottomTabNavigation, Button, Card, ChatBubble, FilterPills, FloatingActionButton, InputField, Navbar, OTPInput, ProductCard, SearchBar } from './components/UI';
import { invoices, products, sales7Days } from './data/mockData';
import { demandPrediction, lowStockProducts, mostSoldProduct, todaysSales } from './utils/analytics';

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Tooltip);

const Layout = ({ children }: { children: React.ReactNode }) => <div className="app-shell p-4 pb-24">{children}</div>;

const Welcome = () => <Layout><div className="text-center"><div className="mx-auto w-fit rounded-2xl bg-tealPrimary p-4 text-2xl text-white">🏪</div><h1 className="mt-3 text-[28px] font-extrabold">VyaparAI</h1><Card className="mt-4 bg-gradient-to-br from-tealPrimary/20 to-tealDark/20"><div className="h-40 rounded-xl bg-white/40" /><p className="mt-4 text-xl font-bold">Run Your Shop Smarter with AI</p><p className="text-sm text-textSecondary">Select your preferred language</p><div className="mt-3 flex justify-center gap-2"><button className="rounded-full bg-white px-4 py-2 text-tealDark">English</button><button className="rounded-full bg-white/60 px-4 py-2">Hindi</button><button className="rounded-full bg-white/60 px-4 py-2">Kannada</button></div></Card><Link to="/category" className="mt-6 block"><Button>Get Started →</Button></Link><p className="mt-3 text-xs text-textSecondary">By continuing you agree to VyaparAI Terms of Service and Privacy Policy</p></div></Layout>;

const Category = () => <Layout><h2 className="text-2xl font-bold">Select Your Shop Type</h2><p className="text-sm text-textSecondary">Choose the category that best describes your business</p><div className="mt-4 grid grid-cols-2 gap-3">{['Medical Store|PHARMACY','Grocery Store|KIRANA','Agriculture|FERTILIZER','Wholesale|BOX SHOP','Dairy Store|BEVERAGE','Cosmetics|PERSONAL CARE','Bakery / Food|FOOD','Hardware Store|TOOLS'].map((c)=><Card key={c}><p className="font-semibold">{c.split('|')[0]}</p><p className="text-xs text-textSecondary">{c.split('|')[1]}</p></Card>)}</div><Link to="/login" className="mt-4 block"><Button>Continue →</Button></Link></Layout>;

const Login = () => <Layout><div className="flex items-center justify-between"><ChevronLeft /><p className="font-bold">VyaparAI</p><span /></div><div className="mt-4 text-center"><div className="mx-auto w-fit rounded-2xl bg-tealPrimary p-4 text-white">🏪</div><h2 className="mt-3 text-2xl font-bold">Welcome back</h2><p className="text-sm text-textSecondary">Enter your phone number to access your business dashboard</p></div><div className="mt-4"><InputField label="Phone Number" placeholder="+91 98765 43210" /><p className="my-4 text-center text-xs text-textSecondary">VERIFICATION</p><OTPInput /><button className="mt-2 text-xs text-tealDark">Resend OTP</button><div className="mt-4 space-y-2"><Link to="/dashboard"><Button>Verify & Login</Button></Link><Button variant="secondary">Create Business Account</Button></div></div><p className="mt-4 text-center text-xs text-textSecondary">Secure AI-Powered Accounting</p></Layout>;

const Dashboard = () => <Layout><Navbar title="VyaparAI" /><p className="mt-3 text-lg font-bold">Good Morning, Rajesh</p><p className="text-sm text-textSecondary">Here is what's happening with your business today</p><div className="mt-3 grid grid-cols-2 gap-3">{[['Today\'s Sales','₹12,450','+12%'],['Customers Today','42','+5%'],['Low Stock Items','5 items','ALERT']].map((x)=><Card key={x[0]}><p className="text-sm text-textSecondary">{x[0]}</p><p className="text-xl font-bold">{x[1]}</p><p className="text-xs text-tealDark">{x[2]}</p></Card>)}</div><Card className="mt-3 bg-gradient-to-r from-tealPrimary to-tealDark text-white"><div className="flex items-center justify-between"><div><p className="font-bold">Ask VyaparAI</p><p className="text-sm text-white/80">Get instant answers about your inventory, sales and reports</p><Link to="/ai-assistant"><button className="mt-2 rounded-xl bg-white px-3 py-2 text-tealDark">Ask Now</button></Link></div><Bot /></div></Card><div className="mt-3 grid grid-cols-3 gap-2">{['Create Bill','Inventory','Sales Analytics','Billing History','Expiry Alerts','New Customer'].map((a)=><Link key={a} to={a==='Create Bill'?'/billing':a==='Inventory'?'/inventory':a==='Billing History'?'/billing-history':a==='Expiry Alerts'?'/expiry-alerts':'/reports'}><Card className="p-3 text-center text-xs font-semibold">{a}</Card></Link>)}</div><BottomTabNavigation /></Layout>;

const Billing = () => { const items = [{ price: 850, qty: 2 }, { price: 1200, qty: 1 }]; const subtotal = items.reduce((s, i) => s + i.price * i.qty, 0); const gst = subtotal * 0.18; const discount = 122; const total = subtotal + gst - discount; return <Layout><div className="flex items-center justify-between"><ChevronLeft /><h2 className="font-bold">Create New Bill</h2><span>⋮</span></div><Card className="mt-3 bg-tealPrimary/10"><div className="flex items-center gap-3"><button className="rounded-full bg-tealPrimary p-3 text-white"><Mic /></button><div><p className="font-semibold">TAP TO SPEAK BILL</p><p className="text-xs text-textSecondary">Add 5 units of Wireless Mouse</p></div></div></Card><div className="mt-3 flex items-center gap-2 rounded-card bg-white px-3 py-2 shadow-soft"><input className="w-full" placeholder="Search products or scan barcode" /><ScanLine size={18} /></div><div className="mt-2"><FilterPills items={['All Categories','Electronics','Groceries']} /></div><div className="mt-3 flex items-center justify-between"><p className="font-bold">Items in Bill</p><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">3 Items</span></div><div className="mt-2 space-y-2"><ProductCard name="Wireless Logitech Mouse" subtitle="M331 Silent Plus" price={850} qty={2} /><ProductCard name="USB-C Fast Charger" subtitle="20W Power Adapter" price={1200} qty={1} /><Button variant="secondary">+ Add New Product</Button></div><Card className="mt-3"><div className="space-y-2 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>₹{subtotal}</span></div><div className="flex justify-between"><span>GST 18%</span><span>₹{gst.toFixed(0)}</span></div><div className="flex justify-between"><span>Discount</span><span>-₹{discount}</span></div><hr/><div className="flex justify-between text-lg font-bold"><span>Grand Total</span><span>₹{total.toFixed(0)}</span></div></div><Button className="mt-3">Generate Invoice</Button></Card></Layout>; };

const BillingHistory = () => <Layout><h2 className="text-2xl font-bold">Billing History</h2><div className="mt-3 space-y-2">{invoices.map((inv)=><Card key={inv.id}><p className="font-semibold">{inv.id}</p><p className="text-sm text-textSecondary">Customer: {inv.customer}</p><p className="text-sm">Total: ₹{inv.total}</p><Button className="mt-2" variant="secondary">View Invoice</Button></Card>)}</div></Layout>;

const Inventory = () => <Layout><div className="flex items-center justify-between"><div><p className="font-bold">VyaparAI</p><h2 className="text-xl font-bold">Inventory Dashboard</h2></div><Bell /></div><div className="mt-3"><SearchBar placeholder="Search items" /></div><div className="mt-2"><FilterPills items={['All Items','Low Stock','Expiring Soon']} /></div><div className="mt-3 space-y-2">{products.map((p)=><Card key={p.name}><p className="font-semibold">{p.name}</p><p className="text-sm text-textSecondary">Category: {p.category}</p><p className="text-sm">Stock: {p.stock} Units</p><p className="text-sm">Expiry: {new Date(p.expiry).toDateString()}</p>{p.stock<20 && <span className="mt-1 inline-block rounded-full bg-amber-100 px-2 py-1 text-xs text-amber-700">LOW STOCK</span>}</Card>)}</div><FloatingActionButton label="+ Add Product" /></Layout>;

const AddProduct = () => <Layout><h2 className="text-2xl font-bold">Add Product</h2><div className="mt-3 space-y-3"><InputField label="Product Name" /><InputField label="Category" /><InputField label="Price" type="number" /><InputField label="Stock Quantity" type="number" /><InputField label="Expiry Date" type="date" /><InputField label="Barcode" /><div className="grid grid-cols-2 gap-2"><Button>Save Product</Button><Button variant="secondary">Cancel</Button></div></div></Layout>;

const ExpiryAlerts = () => <Layout><h2 className="text-2xl font-bold">Expiry Alerts</h2><div className="mt-2"><FilterPills items={['All Items','Critical (<7 days)','Monthly']} /></div><div className="mt-3 space-y-2">{products.filter((p)=> (new Date(p.expiry).getTime()-Date.now())/(1000*3600*24) < 30).map((p)=>{ const days=Math.ceil((new Date(p.expiry).getTime()-Date.now())/(1000*3600*24)); return <Card key={p.name}><p className="font-semibold">{p.name}</p><p className="text-sm">Stock: {p.stock}</p><p className="text-sm">Expires: {new Date(p.expiry).toDateString()}</p><p className={`text-sm ${days<7?'text-red-500':'text-amber-600'}`}>Only {days} days remaining</p>{days<7 && <span className="rounded-full bg-red-100 px-2 py-1 text-xs text-red-600">CRITICAL</span>}<Button className="mt-2" variant="secondary">Apply 20% Off</Button></Card>;})}</div></Layout>;

const Assistant = () => <Layout><h2 className="text-2xl font-bold">Ask VyaparAI</h2><p className="text-xs text-tealDark">ONLINE ASSISTANT</p><div className="mt-3 space-y-2"><ChatBubble role="user" message="Which product sold the most today?" /><ChatBubble role="ai" message="Milk sold 32 packets today. Stock Remaining: 12" /></div><div className="mt-3 flex gap-2">{["Today's Sales",'Low Stock Items','Monthly Report'].map((s)=><button key={s} className="rounded-full bg-white px-3 py-1 text-xs shadow-soft">{s}</button>)}</div><div className="mt-3 rounded-card bg-white p-3 shadow-soft"><input className="w-full" placeholder="Type a business query..." /></div></Layout>;

const Reports = () => {
  const top = mostSoldProduct(); const demand = demandPrediction();
  return <Layout><h2 className="text-2xl font-bold">Reports</h2><div className="mt-3 grid grid-cols-2 gap-2"><Card><p className="text-sm">Today's Sales</p><p className="text-xl font-bold">₹{todaysSales().toLocaleString()}</p></Card><Card><p className="text-sm">Weekly Sales</p><p className="text-xl font-bold">₹{sales7Days.reduce((a,c)=>a+c,0).toLocaleString()}</p></Card><Card><p className="text-sm">Top Product</p><p className="text-xl font-bold">{top?.[0] || 'Milk'}</p></Card><Card><p className="text-sm">Low Stock Items</p><p className="text-xl font-bold">{lowStockProducts().length}</p></Card></div><Card className="mt-3"><Line data={{labels:['D1','D2','D3','D4','D5','D6','D7'],datasets:[{label:'Sales',data:sales7Days,borderColor:'#14B8A6',tension:0.4}]}} /><p className="mt-2 text-xs text-textSecondary">Predicted next week: ₹{Math.round(demand.predicted_next_week).toLocaleString()}</p></Card></Layout>; };

const Placeholder = ({title}:{title:string})=> <Layout><h2 className="text-2xl font-bold">{title}</h2></Layout>;

export default function App() {
  return (
    <Routes>
      <Route path="/" element={<Welcome />} />
      <Route path="/language" element={<Placeholder title="Language Selection" />} />
      <Route path="/category" element={<Category />} />
      <Route path="/login" element={<Login />} />
      <Route path="/otp" element={<Login />} />
      <Route path="/dashboard" element={<Dashboard />} />
      <Route path="/billing" element={<Billing />} />
      <Route path="/billing-history" element={<BillingHistory />} />
      <Route path="/inventory" element={<Inventory />} />
      <Route path="/add-product" element={<AddProduct />} />
      <Route path="/expiry-alerts" element={<ExpiryAlerts />} />
      <Route path="/ai-assistant" element={<Assistant />} />
      <Route path="/reports" element={<Reports />} />
    </Routes>
  );
}
